image: node:lts

before_script:
  - npm ci

stages:
  - lint
  - test
  - build

build site:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  stage: test
  script:
    - npm run test:unit

lint:
  stage: lint
  script:
    - npm run lint