steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push
  args:
  - 'builds'
  - 'submit'
  - '--tag'
  - 'gcr.io/$PROJECT_ID/cybersectech-ui'
  waitFor:
  - '-'
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - '--region=us-central1'
  - 'cybersectech-u'
  - '--image'
  - 'gcr.io/$PROJECT_ID/cybersectech-ui'
  waitFor:
  - 'Push'
